name: Deploy to dev and test
concurrency: dev_environment
on:
  push:
env:
  terraform_version: '1.1.7'
  terraform_working_dir: 'fastly/terraform/'
  fastly_vcl_service_id: 6oKc8cND9r7mE0Aymoo1ST
  fastly_compute_service_id: 06FSzBcnfHpOjSqXwzOxvy
  fastly_top_pops_config: 3BORC4S9SFMY71sIT4HmVD
  fastly_compute_edge_config: 3aFM8b6aSloCCTjRFOxWIo
  domain: dev.polyfill.io
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3
      - uses: actions-rust-lang/setup-rust-toolchain@11df97af8e8102fd60b60a77dfbf58d40cd843b8 # pin@v1
      - name: Set up Fastly CLI
        uses: fastly/compute-actions/setup@6629f0b957369e843434a4c46989556b4dd58ea8 # pin@v11
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          cli_version: '10.4.0'
      - run: fastly compute build --package-name package
      - name: Set cache-key
        id: cache-key
        run: echo "CACHE_KEY=compute-package-$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # pin@v3
        with:
          name: ${{ steps.cache-key.outputs.CACHE_KEY }}
          path: pkg/package.tar.gz
      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # pin@v3
        with:
          path: pkg/package.tar.gz
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}

  deploy-dev-and-purge-cdn:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3
      - name: Set cache-key
        id: cache-key
        run: echo "CACHE_KEY=compute-package-$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - name: Restore compute-package from cache
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # pin@v3
        id: compute-package
        with:
          path: pkg/package.tar.gz
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
          fail-on-cache-miss: true
      - name: 'Terraform Format'
        run: terraform fmt -check
        working-directory: ${{ env.terraform_working_dir }}
      - uses: ./.github/actions/terraform
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_working_dir: fastly/terraform/dev
          fastly-api-token: ${{ secrets.FASTLY_API_KEY }}
          fastly_vcl_service_id: ${{ env.fastly_vcl_service_id }}
          fastly_compute_service_id: ${{ env.fastly_compute_service_id }}
          fastly_top_pops_config: ${{ env.fastly_top_pops_config }}
          fastly_compute_edge_config: ${{ env.fastly_compute_edge_config }}
      - run: "curl -X POST -H \"Fastly-Key: ${{ secrets.FASTLY_API_KEY }}\" https://api.fastly.com/service/${{ env.fastly_vcl_service_id }}/purge_all"
      - run: sleep 60

  dev-end-to-end-test:
    needs: [ deploy-dev-and-purge-cdn ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v3
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # pin@v4.1.0
        with:
          node-version: 18.x
      - name: 'Install test dependencies'
        run: npm ci
        working-directory: "./test"
      - run: npm run test:integration
        working-directory: "./test"
        env:
          HOST: "https://${{ env.domain }}"
